### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by httfore** [felixble/meteor-server-templates#1]
@felixble , 
I can't seem figure out how to do something like 
<table>
    {{each row}}
        <tr>
            <td>
                   {{variable 1}}
            </td>
            <td>
                  {{variable 2}}
           </td>
           <td>
                  {{variable 3}}
           </td>
       </tr>
   {{/each}}
</table>

inside an email.  I'm probably missing something obvious..

**Comment by felixble** [comment]
@KhalilHTM You can use loops just as you are used to in blaze templates. Simply write:
```
{{#each row}}
    Hello {{variable 1}}<br>
{{/each}}
```

I just added a simple test case to demonstrate the usage. Have a look at: https://github.com/felixble/meteor-server-templates/blob/master/server-templates-tests.js#L43.

I will close this issue. If you have any further questions feel free to write a comment.

**Comment by httfore** [comment]
Thank you very much, you've made a great package and it has helped me tremendously!
